// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LivrariaControleEmprestimo.DATA.Models;

[Table("Cliente")]
public partial class Cliente
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("nome")]
    [StringLength(50)]
    [Unicode(false)]
    [DisplayName("Nome")]
    public string Nome { get; set; }

    [Required]
    [Column("cpf")]
    [StringLength(14)]
    [Unicode(false)]
    [DisplayName("CPF")] 
    public string Cpf { get; set; }

    [InverseProperty("IdClienteNavigation")]
    public virtual ICollection<LivroClienteEmprestimo> LivroClienteEmprestimos { get; set; } = new List<LivroClienteEmprestimo>();
}